# ĐỀ BÀI TẬP 3.1.1: **Mảng và ma trận**
<u>Nội dung</u>:
1. Ma trận
2. Hệ phương trình tuyến tính
3. Các bài tập khác

  
<u>Cập nhật</u>: **08/2026**

---
## **1. Ma trận**
---

In [1]:
##------------------------------------------------------------------------------
## Thư viện và các biến toàn cục
##------------------------------------------------------------------------------
import numpy as np
import scipy as sp
from   numpy.linalg import det, inv, matrix_rank

nrows, ncols = 3, 4
min, max     = -10, 50 # giới hạn phạm vi lấy giá trị ngẫu nhiên

In [2]:
##------------------------------------------------------------------------------
## Hien thi ma tran A(m, n) chua cac so nguyen ngau nhien trong khoang [min, max]
##------------------------------------------------------------------------------
## Viet code:
A = np.random.randint(min, max + 1, size=(nrows, ncols))
print("Ma tran A:")
print(A)

Ma tran A:
[[23 31 16 23]
 [12 30 10 -6]
 [16 39 44 32]]


In [3]:
##------------------------------------------------------------------------------
## Nhan 2 dong dau, 2 cot dau cua A voi 2
##------------------------------------------------------------------------------
## Viet code:
A[:2, :] *= 2
A[:, :2] *= 2
print("A sau khi nhan 2 dong dau, 2 cot dau voi 2:")
print(A)

## Binh phuong gia tri 2 dong cuoi
## Viet code:
A[-2:, :] = A[-2:, :] ** 2
print("A sau khi binh phuong 2 dong cuoi:")
print(A)

## Rut trich nhung phan tu cua A co gia tri < 30 va la so le
## Viet code:
ket_qua = A[(A < 30) & (A % 2 != 0)]
print("Cac phan tu < 30 va le:", ket_qua)

A sau khi nhan 2 dong dau, 2 cot dau voi 2:
[[ 92 124  32  46]
 [ 48 120  20 -12]
 [ 32  78  44  32]]
A sau khi binh phuong 2 dong cuoi:
[[   92   124    32    46]
 [ 2304 14400   400   144]
 [ 1024  6084  1936  1024]]
Cac phan tu < 30 va le: []


In [4]:
##------------------------------------------------------------------------------
## Tao ma tran vuong A(m, m) voi gia tri ngau nhien
## Tao ma tran B(m, n) voi gia tri ngau nhien
##------------------------------------------------------------------------------
## Viet code:
m, n = 4, 3
A = np.random.randint(min, max + 1, size=(m, m))
B = np.random.randint(min, max + 1, size=(m, n))
print("A:\n", A)
print("B:\n", B)

## a) Tinh rank(A)
## Viet code:
print("rank(A) =", matrix_rank(A))

## b) Tinh dinh thuc va ma tran nghich dao, neu co
## Viet code:
dinh_thuc = det(A)
print("det(A) =", dinh_thuc)
if dinh_thuc != 0:
    print("inv(A):\n", inv(A))
else:
    print("A khong kha nghich (det = 0)")

## c) Chuyen vi cua A
## Viet code:
print("A.T:\n", A.T)

## d) Tru duong cheo cua A cho alpha = 2
## Viet code:
alpha = 2
A_moi = A.copy()
np.fill_diagonal(A_moi, np.diag(A_moi) - alpha)
print("A sau khi tru duong cheo cho alpha:\n", A_moi)

## e) Ma tran tich A.B
## Viet code:
print("A.B:\n", A.dot(B))

## f) Vecto trong tam (trung binh cac dong)
## Viet code:
vecto_trong_tam = A.mean(axis=0)
print("Vecto trong tam cua A:", vecto_trong_tam)

A:
 [[ 33  -2  -3  -5]
 [ 44   4  14  31]
 [ -2  31  33  13]
 [ 35   2  39 -10]]
B:
 [[23 42 21]
 [27 34 27]
 [20 21  9]
 [14 10 28]]
rank(A) = 4
det(A) = 1416413.9999999995
inv(A):
 [[ 0.02597334  0.00356464  0.00123693 -0.00032829]
 [ 0.04868704 -0.01606945  0.03898719 -0.02347548]
 [-0.03304331  0.00459823 -0.00434619  0.02512613]
 [-0.0282248   0.02719544 -0.00482345 -0.00785222]]
A.T:
 [[ 33  44  -2  35]
 [ -2   4  31   2]
 [ -3  14  33  39]
 [ -5  31  13 -10]]
A sau khi tru duong cheo cho alpha:
 [[ 31  -2  -3  -5]
 [ 44   2  14  31]
 [ -2  31  31  13]
 [ 35   2  39 -12]]
A.B:
 [[ 575 1205  472]
 [1834 2588 2026]
 [1633 1793 1456]
 [1499 2257  860]]
Vecto trong tam cua A: [27.5   8.75 20.75  7.25]


In [5]:
##------------------------------------------------------------------------------
## Tao ma tran A(m, n) voi gia tri ngau nhien
## Tao vecto v(n) voi gia tri ngau nhien
##------------------------------------------------------------------------------
## Viet code:
m, n = 4, 3
A = np.random.randint(min, max + 1, size=(m, n))
v = np.random.randint(min, max + 1, size=(n,))
print("A:\n", A)
print("v:", v)

## Cong vecto v cho moi dong cua ma tran A
## Viet code:
ket_qua_1 = A + v
print("A + v (cach truc tiep):\n", ket_qua_1)

## Ap dung phuong thuc numpy.tile()
## Viet code:
V_tile = np.tile(v, (m, 1))
ket_qua_2 = A + V_tile
print("A + v (dung tile):\n", ket_qua_2)

## Ap dung broadcasting
## Viet code:
ket_qua_3 = A + v[np.newaxis, :]
print("A + v (broadcasting):\n", ket_qua_3)

A:
 [[ 1 27 28]
 [15  9  4]
 [50 32 27]
 [24 42 -8]]
v: [ 3  1 -3]
A + v (cach truc tiep):
 [[  4  28  25]
 [ 18  10   1]
 [ 53  33  24]
 [ 27  43 -11]]
A + v (dung tile):
 [[  4  28  25]
 [ 18  10   1]
 [ 53  33  24]
 [ 27  43 -11]]
A + v (broadcasting):
 [[  4  28  25]
 [ 18  10   1]
 [ 53  33  24]
 [ 27  43 -11]]


In [6]:
##------------------------------------------------------------------------------
## Lưu trữ ma trận thưa (sp matrix)
##------------------------------------------------------------------------------
## Cho ma trận A(3, 4)
A = np.array([[8, 0, 0, 6, 0, 0],
              [0, 0, 9, 0, 0, 4],
              [0, 0, 0, 3, 0, 0]])

## Tính tỷ lệ phần tử = 0 (sparsity)
## Viết code:


## a) Lưu trữ A bằng phương pháp Dictionary of keys (DOK)
##    Tái tạo A để kiểm chứng
## Viết code:


## b) Lưu trữ A bằng phương pháp Coordinate list
##    Tái tạo A để kiểm chứng
## Viết code:


## c) Lưu trữ A bằng phương pháp Compressed Sparse Row (CSR)
##    Tái tạo A để kiểm chứng
## Viết code:


## Tinh ty le phan tu = 0 (sparsity)
## Viet code:
so_phan_tu_khac_0 = np.count_nonzero(A)
tong_phan_tu = A.size
sparsity = 1 - so_phan_tu_khac_0 / tong_phan_tu
print(f"Sparsity = {sparsity:.4f}")

## a) Luu tru A bang phuong phap Dictionary of keys (DOK)
##    Tai tao A de kiem chung
## Viet code:
from scipy.sparse import dok_matrix
A_dok = dok_matrix(A)
print("DOK:", dict(A_dok.items()))
A_tai_tao_dok = A_dok.toarray()
print("Tai tao tu DOK khop voi A:", np.array_equal(A_tai_tao_dok, A))

## b) Luu tru A bang phuong phap Coordinate list
##    Tai tao A de kiem chung
## Viet code:
from scipy.sparse import coo_matrix
A_coo = coo_matrix(A)
print("COO - row:", A_coo.row, "col:", A_coo.col, "data:", A_coo.data)
A_tai_tao_coo = A_coo.toarray()
print("Tai tao tu COO khop voi A:", np.array_equal(A_tai_tao_coo, A))

## c) Luu tru A bang phuong phap Compressed Sparse Row (CSR)
##    Tai tao A de kiem chung
## Viet code:
from scipy.sparse import csr_matrix
A_csr = csr_matrix(A)
print("CSR - indptr:", A_csr.indptr, "indices:", A_csr.indices, "data:", A_csr.data)
A_tai_tao_csr = A_csr.toarray()
print("Tai tao tu CSR khop voi A:", np.array_equal(A_tai_tao_csr, A))

Sparsity = 0.7222


DOK:

 {(np.int32(0), np.int32(0)): np.int64(8), (np.int32(0), np.int32(3)): np.int64(6), (np.int32(1), np.int32(2)): np.int64(9), (np.int32(1), np.int32(5)): np.int64(4), (np.int32(2), np.int32(3)): np.int64(3)}
Tai tao tu DOK khop voi A: True
COO - row: [0 0 1 1 2] col: [0 3 2 5 3] data: [8 6 9 4 3]
Tai tao tu COO khop voi A: True
CSR - indptr: [0 2 4 5] indices: [0 3 2 5 3] data: [8 6 9 4 3]
Tai tao tu CSR khop voi A: True


---
## **2. Hệ phương trình tuyến tính**
---

In [7]:
##------------------------------------------------------------------------------
## Giai he phuong trinh A.X = B
##    Tao ma tran A(m, m) voi gia tri ngau nhien
##    Tao vecto he so B(m) voi gia tri ngau nhien
##    Giai he phuong trinh A.X = B bang 2 cach khac nhau
##------------------------------------------------------------------------------
## Viet code:
m = 3
A = np.random.randint(1, 10, size=(m, m))
B = np.random.randint(1, 10, size=(m,))
print("A:\n", A)
print("B:", B)

if det(A) != 0:
    # Cach 1: dung ma tran nghich dao
    X1 = inv(A).dot(B)
    print("Nghiem (dung inv):", X1)

    # Cach 2: dung numpy.linalg.solve
    X2 = np.linalg.solve(A, B)
    print("Nghiem (dung solve):", X2)
else:
    print("A khong kha nghich, khong the giai bang cach nay")

A:
 [[9 4 9]
 [1 7 6]
 [8 6 1]]
B: [6 5 3]
Nghiem (dung inv): [0.07839388 0.32122371 0.44550669]
Nghiem (dung solve): [0.07839388 0.32122371 0.44550669]


In [8]:
##------------------------------------------------------------------------------
## Giai he phuong trinh:
##    3x + 2y = 5
##    6x + 4y = 1
##------------------------------------------------------------------------------
## Viet code:
A = np.array([[3, 2],
              [6, 4]])
B = np.array([5, 1])

if det(A) != 0:
    X = np.linalg.solve(A, B)
    print("Nghiem:", X)
else:
    # He co the vo nghiem hoac vo so nghiem
    hang_A = matrix_rank(A)
    A_mo_rong = np.column_stack((A, B))
    hang_A_mo_rong = matrix_rank(A_mo_rong)
    if hang_A == hang_A_mo_rong:
        print("He phuong trinh co VO SO NGHIEM")
    else:
        print("He phuong trinh VO NGHIEM")

He phuong trinh VO NGHIEM


In [9]:
##------------------------------------------------------------------------------
## Giai he phuong trinh:
##    3x + 2y = 5
##    6x + 4y = 10
##------------------------------------------------------------------------------
## Viet code:
A = np.array([[3, 2],
              [6, 4]])
B = np.array([5, 10])

if det(A) != 0:
    X = np.linalg.solve(A, B)
    print("Nghiem:", X)
else:
    hang_A = matrix_rank(A)
    A_mo_rong = np.column_stack((A, B))
    hang_A_mo_rong = matrix_rank(A_mo_rong)
    if hang_A == hang_A_mo_rong:
        print("He phuong trinh co VO SO NGHIEM (2 phuong trinh trung nhau)")
    else:
        print("He phuong trinh VO NGHIEM")

He phuong trinh co VO SO NGHIEM (2 phuong trinh trung nhau)


In [10]:
##------------------------------------------------------------------------------
## Mot nha dau tu co von 500K muon dau tu vao 3 co phieu A, B, C.
## Hay xac dinh so tien can dau tu vao A, B, C dua tren nhung rang buoc:
##
##    - Gia tri co phieu A, B, C lan luot la 50, 70, 30
##    - Ty le loi nhuan (du bao) A, B, C lan luot la 12%, 16%, 9%
##    - Mua so co phieu A gap doi so co phieu B
##    - Muc tieu loi nhuan 13%/nam
##------------------------------------------------------------------------------
## Viet code:
## Goi x, y, z lan luot la so tien (K) dau tu vao co phieu A, B, C
## Rang buoc:
##   (1) x + y + z = 500                (tong von dau tu)
##   (2) 0.12x + 0.16y + 0.09z = 0.13*500  (loi nhuan muc tieu)
##   (3) so co phieu A = 2 * so co phieu B  =>  x/50 = 2*(y/70)  =>  x - (100/70)*y = 0
A = np.array([
    [1, 1, 1],
    [0.12, 0.16, 0.09],
    [1, -100/70, 0]
])
B = np.array([500, 0.13 * 500, 0])

if det(A) != 0:
    X = np.linalg.solve(A, B)
    print(f"Dau tu vao co phieu A: {X[0]:.2f}K")
    print(f"Dau tu vao co phieu B: {X[1]:.2f}K")
    print(f"Dau tu vao co phieu C: {X[2]:.2f}K")
else:
    print("He phuong trinh vo nghiem hoac vo so nghiem")

Dau tu vao co phieu A: 253.16K
Dau tu vao co phieu B: 177.22K
Dau tu vao co phieu C: 69.62K


---
## **3. Các bài tập khác**
1. Trộn (merge) 2 mảng có thứ tự A[0..n-1] và B[0..m-1] thành mảng C[0..m+n-1] là mảng được sắp.
2. Viết chương trình kiểm tra các tính chất của một ma trận: đối xứng, tam giác, đường chéo, đơn vị.
---

In [11]:
# Xem cac vi du giai o cac o ben duoi
pass

**Bai giai muc 3 - Cac bai tap khac**

**1. Tron (merge) 2 mang co thu tu A[0..n-1] va B[0..m-1] thanh mang C duoc sap**

In [12]:
def tron_2_mang(A, B):
    i, j = 0, 0
    C = []
    while i < len(A) and j < len(B):
        if A[i] <= B[j]:
            C.append(A[i])
            i += 1
        else:
            C.append(B[j])
            j += 1
    C.extend(A[i:])
    C.extend(B[j:])
    return C

A = [1, 3, 5, 7, 9]
B = [2, 4, 6, 8]
print("Mang sau khi tron:", tron_2_mang(A, B))

Mang sau khi tron: [1, 2, 3, 4, 5, 6, 7, 8, 9]


**2. Kiem tra tinh chat cua ma tran: doi xung, tam giac, duong cheo, don vi**

In [13]:
def la_doi_xung(A):
    return np.array_equal(A, A.T)

def la_tam_giac_tren(A):
    return np.allclose(A, np.triu(A))

def la_tam_giac_duoi(A):
    return np.allclose(A, np.tril(A))

def la_duong_cheo(A):
    return np.allclose(A, np.diag(np.diag(A)))

def la_don_vi(A):
    n = A.shape[0]
    return np.array_equal(A, np.eye(n))

A_test = np.array([[1, 2, 3],
                    [2, 5, 6],
                    [3, 6, 9]])

print("Doi xung:", la_doi_xung(A_test))
print("Tam giac tren:", la_tam_giac_tren(A_test))
print("Tam giac duoi:", la_tam_giac_duoi(A_test))
print("Duong cheo:", la_duong_cheo(A_test))
print("Don vi:", la_don_vi(A_test))

Doi xung: True
Tam giac tren: False
Tam giac duoi: False
Duong cheo: False
Don vi: False
